/* eslint-disable @next/next/no-img-element */

import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

import Content from '../components/content';
import Footer from '../components/footer';

function classNames(...classes: string[]) {
  return classes.filter(Boolean).join(' ')
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Title</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="text-nostalgia-perfume text-center">
          <p>Welcome to the</p>
          <h1 className="leading-none">Stardust<br />Dreamerverse</h1>
          <p>We are a home for the dreamers, the starry eyed space cadets, the lovers and innovators. </p>
          <button type="submit" className="group mx-auto my-4 flex justify-center rounded-md border border-transparent bg-mazzy-star py-2 px-4 text-sm font-medium text-white hover:bg-romantic-rose focus:outline-none focus:ring-2 focus:ring-mazzy-star focus:ring-offset-2">
            Mint a Dreamer
          </button>
        </div>

        {/* This section is basically an InfoWave - still needs work */}
        <Content 
          title="Mission and Values"
          description={"Welcome to the Stardust Dreamerverse. A phygital self expression platform. Come, dream with us, and explore the stardust you’re made of. \nIn our one-of-a-kind web3 ecosystem, we will empower you to fully embody your most authentic self, irl and online. Each season, we will design our own items and curate others from aligned brand partnerships."} 
          button={(
            <button type="submit" className="justify-self-start  my-4 flex rounded-md border border-transparent bg-mazzy-star py-2 px-4 text-sm font-medium text-white hover:bg-romantic-rose focus:outline-none focus:ring-2 focus:ring-mazzy-star focus:ring-offset-2">
              More about us
            </button>
          )}
          img="/img/MissionAndValues.png"
        />

        <Content
          title="Community &amp; Service"
          description={"A great way to onboard a fren to web3 is to get them involved in our Stardust Space Cadet program, where, like scouts, we airdrop different pin patches and badges to our for completing different missions. In the Stardust Shop, these badges can be redeemed for special items and discounts. \nWe make self discovery accessible with community workshops, events, and meditations. We also celebrate each zodiac season and moon cycle with intentional minting, spaces, workshops, and gifts. \nSo, although we believe our good vibes and unique aesthetic will draw in people of all web backgrounds, our web3 community will be an example of the membership and belonging that Stardust Society NFT provides on through blockchain technology."}
          button={(
            <button type="submit" className=" my-4 flex rounded-md border border-transparent bg-periwinkle-blue py-2 px-4 text-sm font-medium text-white hover:bg-purple-illusion focus:outline-none focus:ring-2 focus:ring-periwinkle-blue focus:ring-offset-2">
              View Community Page
            </button>
          )}
          img="/img/community_and_service.png"
          reverse
          bg="nobg"
          titleColor="nostalgia-perfume"
        />
        
        <Content
          title="Stardust Generation"
          description={"What began as 77 total dreamers in the ⭐️ 1/1 genesis collection on Opensea⭐️ expanded into-\n🌙 Stardust Generation,💫 the first generative collection from Stardust Society of 7777 unique dreamers!"}
          button={(
            <button type="submit" className=" my-4 flex rounded-md border border-transparent bg-periwinkle-blue py-2 px-4 text-sm font-medium text-white hover:bg-purple-illusion focus:outline-none focus:ring-2 focus:ring-periwinkle-blue focus:ring-offset-2">
              View Collections
            </button>
          )}
          img="/img/stardust_generation.png"
          bg="nobg"
          titleColor="nostalgia-perfume"
        />

      </main>

      <Footer />
    </div>
  );
};

export default Home;
